# Generated by Django 2.2 on 2020-03-19 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20200319_0132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='attack',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='gold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='hp',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='avatar',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
