# Generated by Django 2.2 on 2020-03-16 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
            ],
        ),
        migrations.CreateModel(
            name='NPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_X', models.IntegerField()),
                ('pos_Y', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NPCAvatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hp', models.IntegerField()),
                ('attack', models.IntegerField()),
                ('npc_type', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_type', models.IntegerField()),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.Expedition')),
                ('section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='course.Section')),
            ],
        ),
        migrations.CreateModel(
            name='User_World',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_finished', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.World')),
            ],
        ),
        migrations.CreateModel(
            name='User_NPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_defeated', models.BooleanField()),
                ('npc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.NPC')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NPCShop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('npc_avatar', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='game.NPCAvatar')),
            ],
        ),
        migrations.AddField(
            model_name='npc',
            name='npc_avatar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.NPCAvatar'),
        ),
        migrations.AddField(
            model_name='npc',
            name='question_bank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.QuestionBank'),
        ),
        migrations.AddField(
            model_name='npc',
            name='world',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.World'),
        ),
        migrations.CreateModel(
            name='CustomWorld',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('background_type', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomNPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos_X', models.IntegerField()),
                ('pos_Y', models.IntegerField()),
                ('custom_world', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.CustomWorld')),
                ('npc_avatar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.NPCAvatar')),
                ('question_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.QuestionBank')),
            ],
        ),
    ]
